package com.pruebatecnica.pruebatecnica.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "clientes")
public class Cliente {

    @DynamoDBHashKey(attributeName = "clienteId")
    @DynamoDBAutoGeneratedKey
    private String clienteId;

    @DynamoDBAttribute(attributeName = "nombre")
    private String nombre;

    @DynamoDBAttribute(attributeName = "saldo")
    private Double saldo = 0.0 ;

    @DynamoDBAttribute(attributeName = "transacciones")
    private List<Transaccion> transacciones;

}